Changes group directionaries names to *_groups
One of the used dictionary names was `input`. This caused the following error:
```bash
BB.input = self._groups['n_exc']
AttributeError: 'NoneType' object has no attribute 'input'
```
To prevent this error from happening the dictionaries were renamed to end on `_groups`,
if though we agreed on a different naming in the BB discussion reflected at #7